// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    ExampleDropdown: typeof import('./src/components/ExampleDropdown.vue')['default']
    ICarbonCode: typeof import('~icons/carbon/code')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiArrowRightThick: typeof import('~icons/mdi/arrow-right-thick')['default']
    IMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IMdiCircleMedium: typeof import('~icons/mdi/circle-medium')['default']
    IMdiInformation: typeof import('~icons/mdi/information')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
  }
}

export { }
